### ISSUE TITLE
update failed for AnAction

### ISSUE THREAD

**Issue by reinderien** [exbin/bined-intellij-plugin#16]
I'm unclear on how or why this happens, but an error is shown in PyCharm - sometimes even if the hex editor is not open:

	update failed for AnAction(org.exbin.deltahex.intellij.DebugViewHexAction) with ID=Debugger.DeltaHexShowAsHex

	java.lang.NoClassDefFoundError: com/intellij/debugger/engine/JavaValue
		at org.exbin.deltahex.intellij.DebugViewHexAction.getDataNode(DebugViewHexAction.java:92)
		at org.exbin.deltahex.intellij.DebugViewHexAction.update(DebugViewHexAction.java:82)
		at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:136)
		at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:256)
		at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:199)
		at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:225)
		at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImpl(ActionToolbarImpl.java:1100)
		at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$000(ActionToolbarImpl.java:53)
		at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$2.updateActionsImpl(ActionToolbarImpl.java:175)
		at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:186)
		at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:3097)
		at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:183)
		at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:132)
		at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:190)
		at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.java:108)
		at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.access$400(ToolbarUpdater.java:40)
		at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyTimerListener.run(ToolbarUpdater.java:158)
		at com.intellij.openapi.actionSystem.impl.WeakTimerListener.run(WeakTimerListener.java:54)
		at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.runListenerAction(ActionManagerImpl.java:1427)
		at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.notifyListeners(ActionManagerImpl.java:1417)
		at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.actionPerformed(ActionManagerImpl.java:1401)
		at javax.swing.Timer.fireActionPerformed(Timer.java:313)
		at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
		at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
		at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
		at java.awt.EventQueue.access$500(EventQueue.java:98)
		at java.awt.EventQueue$3.run(EventQueue.java:715)
		at java.awt.EventQueue$3.run(EventQueue.java:709)
		at java.security.AccessController.doPrivileged(Native Method)
		at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
		at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
		at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:781)
		at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:722)
		at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
		at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
		at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
		at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
		at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
		at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
	Caused by: java.lang.ClassNotFoundException: com.intellij.debugger.engine.JavaValue PluginClassLoader[org.exbin.deltahex.intellij, 0.1.6.1] com.intellij.ide.plugins.cl.PluginClassLoader@23fb04be
		at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
		at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
		... 40 more

**Comment by reinderien** [comment]
Actually this appears to be a duplicate of https://github.com/exbin/bined-intellij-plugin/issues/4
