### ISSUE TITLE
Copy as code doesn't work in debug mode

### ISSUE THREAD

**Issue by hajdam** [exbin/bined-intellij-plugin#20]
Cannot perform copy as code action while in debug mode.

> Copy is not supported
> java.lang.UnsupportedOperationException: Copy is not supported
> 	at org.exbin.bined.intellij.DebugViewDataSource.copy(DebugViewDataSource.java:92)
> 	at org.exbin.bined.swing.basic.DefaultCodeAreaCommandHandler.copyAsCode(DefaultCodeAreaCommandHandler.java:517)
> 	at org.exbin.bined.swing.CodeAreaCore.copyAsCode(CodeAreaCore.java:118)
> 	at org.exbin.bined.intellij.panel.DebugViewPanel.lambda$createContextMenu$1(DebugViewPanel.java:238)
> 	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
> ...

**Comment by hajdam** [comment]
Action can now be performed in version 0.2.0, although there is other error, which causes, that popup menu shows only when invoked above header or row number area.
