### ISSUE TITLE
 0.2.5 Plugin Doesn't Work

### ISSUE THREAD

**Issue by jbis9051** [exbin/bined-intellij-plugin#39]
Plugin doesn't seem to work properly. I'm on Clion 2021.2.3. Unable to delete any characters. Typing is weird and doesn't always work. 

```
java.lang.IllegalStateException: Broken virtual file
	at org.exbin.bined.intellij.BinEdFileDataWrapper.lambda$writeAction$11(BinEdFileDataWrapper.java:455)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:936)
	at org.exbin.bined.intellij.BinEdFileDataWrapper.writeAction(BinEdFileDataWrapper.java:436)
	at org.exbin.bined.intellij.BinEdFileDataWrapper.remove(BinEdFileDataWrapper.java:407)
	at org.exbin.bined.operation.swing.DeleteCodeEditDataOperation.appendEdit(DeleteCodeEditDataOperation.java:82)
	at org.exbin.bined.operation.swing.command.EditCodeDataCommand.appendEdit(EditCodeDataCommand.java:131)
	at org.exbin.bined.operation.swing.CodeAreaOperationCommandHandler.deleteAction(CodeAreaOperationCommandHandler.java:536)
	at org.exbin.bined.operation.swing.CodeAreaOperationCommandHandler.backSpacePressed(CodeAreaOperationCommandHandler.java:498)
	at org.exbin.bined.operation.swing.CodeAreaOperationCommandHandler.keyPressed(CodeAreaOperationCommandHandler.java:268)
	at org.exbin.bined.swing.CodeAreaCore$2.keyPressed(CodeAreaCore.java:91)
	at java.desktop/java.awt.AWTEventMulticaster.keyPressed(AWTEventMulticaster.java:257)
	at java.desktop/java.awt.Component.processKeyEvent(Component.java:6610)
	at java.desktop/javax.swing.JComponent.processKeyEvent(JComponent.java:2852)
	at java.desktop/java.awt.Component.processEvent(Component.java:6429)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1962)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:879)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1158)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:1018)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:844)
	at com.intellij.ide.IdeKeyboardFocusManager.dispatchEvent(IdeKeyboardFocusManager.java:42)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4908)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue.dispatchKeyEvent(IdeEventQueue.java:801)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.io.IOException: Unable to skip data
	at org.exbin.bined.intellij.StreamUtils.skipInputStreamData(StreamUtils.java:164)
	at org.exbin.bined.intellij.BinEdFileDataWrapper.lambda$remove$9(BinEdFileDataWrapper.java:413)
	at org.exbin.bined.intellij.BinEdFileDataWrapper.lambda$writeAction$11(BinEdFileDataWrapper.java:439)
	... 52 more
```

**Comment by jbis9051** [comment]
Plugin seems to be working on 0.2.4 so must be a 0.2.5 issue

**Comment by hajdam** [comment]
Hi, thanks for reporting this.
Seems like I can reproduce this error on Clion 2021.2.4 so I'll try to take look into it.

As this is an issue with virtual files handling, as a workaround it should be possible to use "Open as Binary" from context menu instead of directly opening project files for now.

**Comment by hajdam** [comment]
Should be fixed in current development build.
https://bined.exbin.org/download/?bined-intellij-plugin.zip

**Comment by jbis9051** [comment]
Looks good
